### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by AHpxChina** [Wolfteam/GenshinDb#11]
This is a great app, it should add support for more languages, and I am willing to provide simplified Chinese and traditional Chinese translations

**Comment by Wolfteam** [comment]
Hiho, if you would like to help me translate the app, contact me via email: miraisoft20@gmail.com or discord: wolfteam20#4750

**Comment by AHpxChina** [comment]
I added your discord, but you have not yet accepted the application

**Comment by AHpxChina** [comment]
I'm working on Chinese translation now
