### ISSUE TITLE
New pull

### ISSUE THREAD

**Issue by Nisseliy** [Wolfteam/GenshinDb#12]
When will hao be added? And also i sent a review on google play. Do you read those? Anw i think if we had an inventory with all the weapons and characters we have pulled in the wish section it would be awesome like you can look at what you got and all. And lots of thanks for the app ❤❤ from nisseliy

**Comment by Wolfteam** [comment]
Hu Tao will be added when it gets released.
Yep I do read the reviews on google play.
The wish simulator is provided by https://github.com/uzair-ashraf/genshin-impact-wish-simulator , I just added it to the app

**Comment by Wolfteam** [comment]
Hu tao was added in ccde134caf1dc3a7ad267fc81ca3235ac02c94ac
