### ISSUE TITLE
Any possibility of Chinese Translation?

### ISSUE THREAD

**Issue by 2O48** [Wolfteam/GenshinDb#18]
I'm a Chinese player and I love the app so much it's a masterpiece, so helpful. While the app only has 2 languages. So if possible I would like to do some translation work. Thank you!

**Comment by Wolfteam** [comment]
Hiho, sure, please contact me via email (miraisoft20@gmail.com) or discord (wolfteam20#4750)

**Comment by Wolfteam** [comment]
This is fixed now in #22
