### ISSUE TITLE
[Localization] Russian/Русский

### ISSUE THREAD

**Issue by kasproTV** [Wolfteam/GenshinDb#21]
Hey! I am a Russian player and noticed your app. I would like to help translate your application into Russian.

**Comment by kchayyy** [comment]
I would like to help too.

**Comment by Wolfteam** [comment]
Hiho, sure, please contact me via email (miraisoft20@gmail.com) or discord (wolfteam20#4750)

**Comment by HencoDesu** [comment]
I see some typos in merged PR. How can I help to fix it?

**Comment by kchayyy** [comment]
Hi, I sent you a friend request in Discord. Ivan LoL#7102

пт, 5 мар. 2021 г., 01:37 Efrain Bastidas ***@***.***>:

**Comment by Wolfteam** [comment]
Hiho, translations are pretty much completed
