### ISSUE TITLE
help with partial Spanish

### ISSUE THREAD

**Issue by Sebilebi** [Wolfteam/GenshinDb#27]
I've been speaking Spanish all my life, if you want I could help you translate the app into Spanish completely, by the way, I love your app.

**Comment by Wolfteam** [comment]
Hiho, I think almost all the app is translated to Spanish (except for some weapons / artifacts that haven't been released yet, and for this cases I prefer waiting until they are released because they could change)

**Comment by Sebilebi** [comment]
ok, if you need help, don't hesitate to ask me

**Comment by Wolfteam** [comment]
> ok, if you need help, don't hesitate to ask me

Sure, btw if you notice a typo or something is not well translated let me know
