### ISSUE TITLE
Suggestion?

### ISSUE THREAD

**Issue by UhmIDK** [Wolfteam/GenshinDb#36]
Why not add a character template? (eg. Select character> equipment and artifacts you want to focus on that can be marked as acquired along with the character calculator that's already available)

**Comment by Wolfteam** [comment]
I think what I'm currently working on will fix this :)
For now I'll leave this one open until [this gets merged](https://github.com/Wolfteam/GenshinDb/tree/feature/my_inventory)

**Comment by Wolfteam** [comment]
Probably fixed in #40
