### ISSUE TITLE
About translate the app to Vietnamese

### ISSUE THREAD

**Issue by AsrieltheGoat** [Wolfteam/GenshinDb#37]
Hi, I quite like the app. The UI is simple and easy to understand but my friend don't know anything about English so I hope I can help you translate the app to Vietnamese

**Comment by Wolfteam** [comment]
Hiho, sure, you can find the general file [Here](https://github.com/Wolfteam/GenshinDb/blob/main/lib/l10n/intl_en.arb) and the main one [here](https://github.com/Wolfteam/GenshinDb/blob/main/assets/i18n/en.json)
In the readme file there is a simple explanation on how to translate those files.
Also, you can contact me via email: miraisoft20@gmail.com or discord wolfteam20#4750
