### ISSUE TITLE
Can we have a option to save what we put into the calculator?

### ISSUE THREAD

**Issue by Lannanville37** [Wolfteam/GenshinDb#39]
i love this app and everything youve done into it but i noticed that everytime i do something with the calculator it immediately gets deleted once i close and re open the app, it gets a bit annoying cause ive been wanting to raise characters and having to reput all the info for the character or weapon gets a bit annoying. so if we could have a way to pin them or save them into the calculator so we dont have to re enter anything that would be great. But seriously this app has been a life saver and its gotten my team from doing nothing to being super OP.

**Comment by Wolfteam** [comment]
This will be fixed once #40 gets merged

**Comment by Wolfteam** [comment]
Fixed in #40
