### ISSUE TITLE
Translation Spanish

### ISSUE THREAD

**Issue by Haakuji** [Wolfteam/GenshinDb#48]
I love the app but some things are missing in Spanish, so I thought I would try to translate the parts missing 🥺 and maybe I can check the phrases because some of them are wrong. Can I help?

**Comment by Wolfteam** [comment]
Hiho, sure, you can find the general file [Here](https://github.com/Wolfteam/GenshinDb/blob/main/lib/l10n/intl_es_ES.arb) and the main one [Here](https://github.com/Wolfteam/GenshinDb/blob/main/assets/i18n/es.json)
In the readme file there is a simple explanation on how to translate those files.
Also, you can contact me via email: miraisoft20@gmail.com or discord wolfteam20#4750

**Comment by Blask0** [comment]
https://github.com/Wolfteam/GenshinDb/pull/50

> Hiho, sure, you can find the general file [Here](https://github.com/Wolfteam/GenshinDb/blob/main/lib/l10n/intl_es_ES.arb) and the main one [Here](https://github.com/Wolfteam/GenshinDb/blob/main/assets/i18n/es.json)
> In the readme file there is a simple explanation on how to translate those files.
> Also, you can contact me via email: [miraisoft20@gmail.com](mailto:miraisoft20@gmail.com) or discord wolfteam20#4750

**Comment by sxanel** [comment]
Greetings, how can I help translate into Spanish?

**Comment by Wolfteam** [comment]
> Greetings, how can I help translate into Spanish?

Hiho, sure, you can find the general file [Here](https://github.com/Wolfteam/GenshinDb/blob/main/lib/l10n/intl_es_ES.arb) and the main one [Here](https://github.com/Wolfteam/GenshinDb/blob/main/assets/i18n/es.json)
In the readme file there is a simple explanation on how to translate those files.
Also, you can contact me via email: miraisoft20@gmail.com or discord wolfteam20#4750
