### ISSUE TITLE
mistakes

### ISSUE THREAD

**Issue by nsoll** [Wolfteam/GenshinDb#79]
there are mistakes in the amount of mora for some weapons, instead of 45,000 it is written 450,000 (prototype rancour, blackcliff pole, dragon's bane, royal spear, prototype crescent), can you double-check and fix it, please

**Comment by Wolfteam** [comment]
This was fixed in b1ab1c8805a785253bf625a6cf81b34cc81834e5  I just haven't pushed the fix to the play store

**Comment by nsoll** [comment]
thank you!
