### ISSUE TITLE
Isn't The Unforged good for DPS Noelle?

### ISSUE THREAD

**Issue by Rainaria** [Wolfteam/GenshinDb#91]
I've noticed that there isn't The Unforged in DPS Noelle build, but why? Isn't it one of the best claymores for her because of her shield and ATK increase effect of the claymore?

**Comment by Wolfteam** [comment]
Hiho, "The Unforged" can be used on the dps build, but I won't say that it's one of the best for noelle.
In any case, will add it to the dps build on the app
