### ISSUE TITLE
Dúvida sobre check in diário.

### ISSUE THREAD

**Issue by Ramos2801** [Wolfteam/GenshinDb#94]
Como funciona o check in diário??

**Comment by Wolfteam** [comment]
You just log in and get the daily rewards

**Comment by Ramos2801** [comment]
Eu faço o login e o app diz que nenhum personagem foi criado! Como crio o
personagem??

Em sáb, 24 de jul de 2021 01:54, Efrain Bastidas ***@***.***>
escreveu:

**Comment by Wolfteam** [comment]
You need to link your game account (HERE)[https://account.mihoyo.com/?lang=en#/login?cb_route=%2Faccount%2FaccountInfo]
